title: ModbusCore v3.0
description: Modern, lightweight, dependency-injection-based Modbus protocol stack
theme: jekyll-theme-cayman
show_downloads: true

# GitHub repo info
repository: lgili/modbuscore
github_username: lgili

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
